services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=localhost 
      - DB_PORT=3006
      - DB_NAME=auth_service
    depends_on:
      - db 
    networks:
      - app-networks
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root 
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-networks
    ports:
      - "3306:3306"

networks:
  app-networks:
    driver: bridge

volumes:
  db-data: